theme: minima
title: Terra Nullius
description: Alexei Lednev's personal blog
author:
  name: Alexei Lednev
  email: alexei.led@gmail.com
markdown: GFM
baseurl: ""
url: "https://alexei-led.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

  # Show excerpts on the home page
  show_excerpts: true

  # Header pages
  header_pages:
    - about.md

  # Generate social links in footer
  social_links:
    - platform: github
      user_url: "https://github.com/alexei-led"
      title: "GitHub"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
