baseurl = "https://alexei-led.github.io"
title = "Terra Nullius"
canonifyURLs = true
theme = "zen"
paginate = 10
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License"
disqusShortname = "gaia-blog"

[params]
  twitter = "alexeiled"
  twitterName = "alexeiled"
  githubName = "alexei-led"
  description = "The Programming Blog"
  google_analytics = "UA-71802462-1"
