baseurl = "https://alexei-led.github.io"
title = "Terra Nullius"
canonifyURLs = true
theme = "noteworthy"
paginate = 10
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License"
disqusShortname = "gaia-blog"
googleAnalytics = "UA-71802462-1"

[params]
  medium = "https://medium.com/@alexeiled"
  twitter = "https://twitter.com/alexeiled"
  github = "https://github.com/alexei-led"
