remote_theme: "jekyll/minima@1e8a445"
title: Terra Nullius
description: Alexei Lednev's personal blog
markdown: GFM
baseurl: ""
url: "https://alexei-led.github.io/blog"

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

  # Generate social links in footer
  social_links:
    github: alexei-led
